rootProject.name = 'customizations'

include ':my-empty-project'
include ':my-custom-job'
include ':my-listener'
include ':my-openapi-project'
include ':my-file-processor'
include ':my-gitpr-project'
include ':customization-rest-controller'
include ':my-custom-function'
include 'my-description-swagger-endpoint'

